# Generated by Django 3.2.3 on 2021-06-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='Contact',
        ),
    ]
